// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/css": {
    params: {};
  };
  "/radix": {
    params: {};
  };
  "/gsap": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/css" | "/radix" | "/gsap" | "/*";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./routes/css-playground/css-demo.tsx": {
    id: "routes/css-playground/css-demo";
    page: "/css";
  };
  "./routes/radix-playground/index.tsx": {
    id: "routes/radix-playground/index";
    page: "/radix";
  };
  "./routes/gsap-playground/gsap-demo.tsx": {
    id: "routes/gsap-playground/gsap-demo";
    page: "/gsap";
  };
  "./routes/404.tsx": {
    id: "routes/404";
    page: "/*";
  };
};